# Generated by Django 5.2.12 on 2026-03-10 22:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'CPF deve conter 11 números')], verbose_name='CPF')),
                ('nome', models.CharField(max_length=70, validators=[django.core.validators.MinLengthValidator(25, 'O nome deve conter entre 25 e 70 caracteres')], verbose_name='Nome')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{10,11}$', 'Telefone deve conter 10 ou 11 números')], verbose_name='Telefone')),
                ('estado', models.CharField(choices=[('RJ', 'Rio de Janeiro'), ('SP', 'São Paulo'), ('MG', 'Minas Gerais'), ('ES', 'Espírito Santo'), ('BA', 'Bahia'), ('RS', 'Rio Grande do Sul'), ('PR', 'Paraná')], max_length=2, verbose_name='Estado')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Gênero')),
                ('contato_pref', models.CharField(choices=[('EMAIL', 'Email'), ('TELEFONE', 'Telefone'), ('CELULAR', 'Celular')], max_length=10, verbose_name='Contato Preferencial')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('usuario', models.CharField(max_length=100, verbose_name='Usuário')),
                ('senha', models.CharField(max_length=256, verbose_name='Senha')),
            ],
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=70, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=70, verbose_name='Nome')),
                ('preco_compra', models.FloatField(verbose_name='Preço de Compra')),
                ('preco_venda', models.FloatField(verbose_name='Preço de Venda')),
                ('cor', models.CharField(choices=[('AZ', 'Azul'), ('VD', 'Verde'), ('VM', 'Vermelho'), ('AM', 'Amarelo'), ('PR', 'Preto'), ('BR', 'Branco'), ('MR', 'Marrom')], max_length=2, verbose_name='Cor')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Imagem')),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fabricante', verbose_name='Fabricante')),
            ],
        ),
    ]
